### ISSUE TITLE
Filtering of dates is not working.

### ISSUE THREAD

**Issue by jeroenleenarts** [AppForce1/lilygo-t5-47-plus-esphome#1]
Sample content:

For some reason this is not filtered due to the lines here: https://github.com/AppForce1/lilygo-t5-47-plus-esphome/blob/main/python_scripts/esp_calendar_data_conversion.py#L83

```
todays_day_name: maandag
todays_date_month_year: januari 2025
closest_end_time: 0
entries:
  - date: "2025-01-28"
    day: 28
    is_today: 0
    day_name: di
    all_day: []
    other:
      - start: "2025-01-28T08:30:00+01:00"
        end: "2025-01-28T14:00:00+01:00"
        summary: XYZ
        calendar_name: Family
        location_name: A location
      - start: "2025-01-28T08:30:00+01:00"
        end: "2025-01-28T08:45:00+01:00"
        summary: A conversation
        calendar_name: Family
        location_name: Telefoon
      - start: "2025-01-28T09:15:00+01:00"
        end: "2025-01-28T11:15:00+01:00"
        summary: Schouw WP
        calendar_name: Family
        location_name: Somewhere
      - start: "2025-01-28T13:45:00+01:00"
        end: "2025-01-28T15:15:00+01:00"
        summary: A drive
        calendar_name: Family
      - start: "2025-01-28T15:00:00+01:00"
        end: "2025-01-28T18:30:00+01:00"
        summary: Some sports
        calendar_name: Family
        location_name: A venue
      - start: "2025-01-28T19:30:00+01:00"
        end: "2025-01-28T21:00:00+01:00"
        summary: Another sports
        calendar_name: Family
        location_name: A sports place
friendly_name: ESP Calendar Data

```
